name: Build and Package Function

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js (v22)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Create ZIP Archive
        run: |
          mkdir package
          cp -r dist package/
          cp package.json package/
          cd package
          zip -r ../function-package.zip .
